from sqlmodel import Session, select
from .models import School, Offer


def seed_data(session: Session):
    if session.exec(select(School)).first():
        return

    schools = [
        School(
            name="UNIS Hanoi",
            slug="unis-hanoi",
            curriculum="IB PYP / MYP / Diploma",
            tuition_range="$15,000 – $35,000",
            district="Tay Ho",
            image_url="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=60",
            summary="Best for full IB continuity and globally mobile families.",
            accreditation="CIS, NEASC, IBO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.unishanoi.org",
            founded_year="1988",
            total_students="~1,600",
            class_size_max="22",
            address="G9 Ciputra, Phu Thuong Ward, Tay Ho, Hanoi",
            facilities="Olympic swimming pool|Sports complex|Black box theatre|Science labs|Makerspace|Library|Counselling centre",
            pros="Full IB continuum from nursery to DP|Internationally diverse student body (60+ nationalities)|Strong university counselling record|Beautiful lakeside campus with excellent facilities",
            cons="Among the highest fees in Hanoi|Long waitlists for popular year groups|Tay Ho location can mean long commutes from the south",
            university_pathways="IB Diploma → strong placements at UK, US, Canadian, Australian universities; historically 95%+ receive their first-choice offer",
            admissions_timeline="October: Application opens|January: Early decision deadline|March: Rolling admissions continue|May: Final offers sent|August: New student orientation",
            required_documents="Completed application form|Birth certificate|Latest two years school reports|Teacher recommendation letters|Medical/vaccination records|Copy of passport",
            faq_questions="Is UNIS a good school for non-IB families?|What is the language support programme?|How competitive is entry for Grade 6?|Does UNIS offer scholarships?|What after-school activities are available?",
            faq_answers="UNIS only offers the IB curriculum, so families committed to an alternative pathway (e.g. A-Levels or AP) should consider other schools.|English is the primary language; an English Language Learning (ELL) programme supports non-native speakers in all year groups.|Grade 6 (start of MYP) is one of the more competitive entry points. Apply early and ensure strong academic records.|UNIS offers a small number of merit-based scholarships for Grade 9 entry each year. Contact the admissions office directly.|Over 80 extracurricular clubs and activities including Model UN, robotics, performing arts, and 30+ sports teams.",
        ),
        School(
            name="British International School Hanoi",
            slug="bis-hanoi",
            curriculum="British National Curriculum + IGCSE + IB Diploma",
            tuition_range="$18,000 – $32,000",
            district="Long Bien",
            image_url="https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=60",
            summary="Strong UK pathway with the option to switch to IB in senior years.",
            accreditation="BSO, Ofsted-inspected, IBO (Diploma only)",
            language_of_instruction="English",
            age_range="2–18",
            website_url="https://www.bishanoi.com",
            founded_year="1997",
            total_students="~1,200",
            class_size_max="20",
            address="Vinhomes Riverside, Long Bien, Hanoi",
            facilities="25m swimming pool|Multi-sport AstroTurf|Performing arts centre|STEAM labs|Dedicated sixth-form centre|Early years outdoor play areas",
            pros="Rigorous British curriculum familiar to UK-educated parents|Dual exit pathway (A-Level track or IB Diploma)|Vinhomes Riverside campus is safe and leafy|Strong pastoral care system",
            cons="Long Bien location is far from the city centre and western expat areas|British curriculum may feel rigid compared to IB|Smaller community than UNIS",
            university_pathways="IGCSE → A-Levels or IB Diploma → UK universities (Russell Group, Oxbridge successes); US/Australian applications also supported",
            admissions_timeline="September: Applications open for following academic year|November: Priority deadline for scholarship consideration|February: Main admissions round|April: Final places offered|August: Welcome week",
            required_documents="Application form|Passport copy|Last two years school reports|Head teacher reference|Medical records|Proof of address",
            faq_questions="Can my child join mid-year?|What language support is offered?|Is there a sibling discount?|How does the A-Level vs IB choice work?|What is the school's university placement record?",
            faq_answers="BIS accepts mid-year applications subject to space availability. Contact admissions with your child's current school reports for an initial assessment.|An EAL (English as an Additional Language) programme supports students whose first language is not English, from beginner to advanced levels.|BIS offers a 10% sibling discount on the second child's tuition fees.|Students choose between A-Levels and IB Diploma at the start of Year 12 (age 16). Both pathways are well-supported, and a guidance programme helps families decide.|In recent years over 90% of leavers received offers from their first or second choice universities, including several Oxbridge and Ivy League placements.",
        ),
        School(
            name="Concordia International School Hanoi",
            slug="concordia-hanoi",
            curriculum="US Common Core + Advanced Placement (AP)",
            tuition_range="$14,000 – $28,000",
            district="Long Bien",
            image_url="https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=60",
            summary="Top choice for US university-bound families seeking rigorous AP preparation.",
            accreditation="WASC, ACSI, College Board (AP)",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.concordiahanoi.org",
            founded_year="1999",
            total_students="~800",
            class_size_max="18",
            address="Vinhomes Riverside, Long Bien, Hanoi",
            facilities="Full-size gymnasium|Swimming pool|Art studios|Science labs|Chapel|Sports fields",
            pros="Strong AP programme widely recognised by US colleges|Smaller class sizes than larger international schools|Strong Christian values community for faith-based families|Very competitive tuition relative to comparable schools",
            cons="Christian faith orientation may not suit all families|Smaller overall enrolment limits the range of extracurriculars|US curriculum less recognised by UK/European universities",
            university_pathways="AP → US colleges; strong track record at US liberal arts colleges and state universities; growing placements in Canada and Australia",
            admissions_timeline="October: Applications open|December: Early decision deadline|March: Rolling admissions|May: Placement confirmation|August: New student welcome week",
            required_documents="Application and personal statement|Passport and birth certificate|Last two years transcripts|Two teacher references|Standardised test scores (if available)|Medical and immunisation records",
            faq_questions="Is Concordia only for Christian families?|How many AP courses are offered?|What is the student-teacher ratio?|Does Concordia support ESL students?|Are there merit scholarships available?",
            faq_answers="While Concordia has a Christian foundation and holds chapel services, students of all faiths are warmly welcomed and respected.|Concordia offers 18 AP courses across STEM, humanities, and the arts, one of the broadest AP selections in Hanoi.|The average student-teacher ratio is approximately 8:1, enabling close academic support.|ESL support is available from Kindergarten through Grade 12, with pull-out and in-class support models.|Merit-based scholarships are available for Grade 9 and Grade 11 entry; contact admissions for criteria and application details.",
        ),
        School(
            name="Hanoi International School",
            slug="hanoi-international-school",
            curriculum="IB PYP / MYP / Diploma",
            tuition_range="$12,000 – $25,000",
            district="Dong Da",
            image_url="https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=60",
            summary="Central location with competitive IB fees; popular with long-term expats.",
            accreditation="CIS, IBO",
            language_of_instruction="English",
            age_range="5–18",
            website_url="https://www.hisvietnam.com",
            founded_year="1994",
            total_students="~500",
            class_size_max="20",
            address="1 Giang Vo Street, Dong Da, Hanoi",
            facilities="Library|Science labs|Art and music rooms|Sports hall|Swimming pool access (off-site partner)",
            pros="Most central location — easy access from Ba Dinh, Hoan Kiem and Dong Da|Full IB at a significantly lower price point than UNIS|Smaller community fosters tight-knit parent network|Strong Vietnamese culture integration",
            cons="Smaller campus with fewer on-site sports facilities|Less international diversity than larger schools|No early years programme (starts at Grade 1)",
            university_pathways="IB Diploma with support for UK, US, Australian, and Vietnamese university applications",
            admissions_timeline="September: Open house and applications begin|January: Rolling admissions|April: Final year group confirmations|August: Orientation day",
            required_documents="Application form|Passport copy|Previous school reports (last 2 years)|Immunisation records|Recommendation letter from current teacher",
            faq_questions="Does HIS offer a Kindergarten programme?|Is Vietnamese language taught?|How large are the class sizes?|What makes HIS different from UNIS?|Are transport options available?",
            faq_answers="HIS currently starts from Grade 1 (age 5-6). Families seeking early years provision should consider UNIS or BIS.|Yes — Vietnamese language and culture is a core part of the curriculum from Grade 1, making HIS popular with families planning a longer-term stay in Vietnam.|Classes average 16-18 students, smaller than most Hanoi international schools.|HIS is considerably more affordable and more centrally located. UNIS is larger, more internationally diverse, and has superior sports facilities. Both offer the full IB continuum.|HIS partners with a private bus service that covers most Hanoi districts. Costs are separate from tuition.",
        ),
        School(
            name="Lycée Français Alexandre Yersin",
            slug="lycee-francais-hanoi",
            curriculum="French National Curriculum + International Baccalaureate",
            tuition_range="$8,000 – $20,000",
            district="Dong Da",
            image_url="https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=1200&q=60",
            summary="The top choice for French-speaking families and those seeking a bilingual French-English education.",
            accreditation="AEFE (French Ministry of Education), IBO",
            language_of_instruction="French (primary) + English",
            age_range="3–18",
            website_url="https://www.lyceeyersin.com",
            founded_year="1994",
            total_students="~700",
            class_size_max="25",
            address="2A Nguyen Gia Thieu, Dong Da, Hanoi",
            facilities="Gymnasium|Library|Science labs|Art rooms|Canteen|Outdoor play areas",
            pros="Most affordable international school for the quality offered|Bilingual French-English programme|Strong academic rigour following French national curriculum|AEFE accreditation means qualifications recognised worldwide",
            cons="Instruction primarily in French — difficult entry for non-French speakers|English proficiency of graduates can lag compared to English-medium schools|Smaller campus with limited sports facilities",
            university_pathways="Baccalauréat → French grandes écoles and universities; IB Diploma track available for senior students; growing placements in UK and US",
            admissions_timeline="October: Application period opens|February: Language assessment for non-francophone applicants|April: Placement offers|June: Enrolment confirmation|September: School year begins",
            required_documents="Application form|Passport copy|School reports (French or translated)|French language assessment (for non-native speakers)|Vaccination record",
            faq_questions="Can non-French-speaking children join?|Is there an English-medium track?|What is the Baccalauréat worth internationally?|Are there scholarships for non-French nationals?|How does the school handle the French-Vietnamese cultural mix?",
            faq_answers="Non-French speakers are accepted but must complete a language assessment. An immersion programme supports beginners, though parents should expect a challenging first year.|English is taught as a second language throughout, and senior students can choose between the French Baccalauréat and the IB Diploma (taught in English).|The French Baccalauréat is recognised by universities across Europe, North America, and Australia. It is considered equivalent or superior to A-Levels by most UK universities.|AEFE scholarships are available to French nationals through the French government; the school also offers limited need-based bursaries to all nationalities.|The school has a large Vietnamese-French student body alongside expats, creating a uniquely local international atmosphere that many parents value highly.",
        ),
    ]

    for s in schools:
        session.add(s)
    session.commit()

    loaded = session.exec(select(School)).all()
    school_map = {s.slug: s.id for s in loaded}

    offers = [
        Offer(
            school_id=school_map["unis-hanoi"],
            title="Grade 9 Merit Scholarship 2026",
            offer_type="Scholarship",
            detail="Partial scholarship covering up to 20% of tuition for academically outstanding Grade 9 applicants. Requires minimum B average and two teacher recommendations.",
            deadline="2026-07-15",
            source_url="https://www.unishanoi.org/admissions/scholarships",
            verification_status="School-confirmed",
        ),
        Offer(
            school_id=school_map["bis-hanoi"],
            title="Early Enrolment Discount — 5% off tuition",
            offer_type="Discount",
            detail="Families who confirm enrolment and pay the deposit before 30 June 2026 receive a 5% reduction on the full-year tuition fee.",
            deadline="2026-06-30",
            source_url="https://www.bishanoi.com/admissions/fees",
            verification_status="School-confirmed",
        ),
        Offer(
            school_id=school_map["bis-hanoi"],
            title="Sibling Discount — 10% on second child",
            offer_type="Discount",
            detail="Families enrolling a second child receive 10% off that child's annual tuition. Discount applies for as long as both children are enrolled.",
            deadline="2026-12-31",
            source_url="https://www.bishanoi.com/admissions/fees",
            verification_status="School-confirmed",
        ),
        Offer(
            school_id=school_map["concordia-hanoi"],
            title="AP Excellence Scholarship",
            offer_type="Scholarship",
            detail="Merit scholarship for incoming Grade 9 and Grade 11 students with demonstrated academic excellence. Award value: $2,000–$5,000 per year, renewable.",
            deadline="2026-12-01",
            source_url="https://www.concordiahanoi.org/admissions/scholarships",
            verification_status="Source-verified",
        ),
        Offer(
            school_id=school_map["concordia-hanoi"],
            title="Refer-a-family enrollment fee waiver",
            offer_type="Fee Waiver",
            detail="Current Concordia families who refer a new family receive a waiver of the $500 enrolment fee for their next academic year.",
            deadline="2026-08-31",
            source_url="https://www.concordiahanoi.org/admissions",
            verification_status="Source-verified",
        ),
        Offer(
            school_id=school_map["hanoi-international-school"],
            title="New family welcome discount — 3 months free bus",
            offer_type="Fee Waiver",
            detail="New families joining HIS for the 2026–27 academic year receive three months of complimentary school bus service (valued at ~$450).",
            deadline="2026-07-31",
            source_url="https://www.hisvietnam.com/admissions",
            verification_status="Source-verified",
        ),
        Offer(
            school_id=school_map["lycee-francais-hanoi"],
            title="AEFE Scholarship for French Nationals",
            offer_type="Scholarship",
            detail="French government scholarships available through the AEFE network for French nationals based on financial need. Can cover up to 100% of tuition.",
            deadline="2026-05-31",
            source_url="https://www.lyceeyersin.com/scolarite/bourses",
            verification_status="School-confirmed",
        ),
        Offer(
            school_id=school_map["lycee-francais-hanoi"],
            title="Early registration discount — €500 off",
            offer_type="Discount",
            detail="Families who register and pay the deposit before 31 March 2026 receive €500 off the annual tuition fee for the following academic year.",
            deadline="2026-03-31",
            source_url="https://www.lyceeyersin.com/scolarite",
            verification_status="School-confirmed",
            active=False,
        ),
    ]

    for o in offers:
        session.add(o)
    session.commit()
