from sqlmodel import Session, select
from .models import School, Offer

# Unsplash image pool (school / campus themed)
_IMGS = [
    "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1567168539153-4a78e5fd1ad4?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=1200&q=60",
    "https://images.unsplash.com/photo-1548449112-96a38a643324?auto=format&fit=crop&w=1200&q=60",
]


def _img(i: int) -> str:
    return _IMGS[i % len(_IMGS)]


def seed_data(session: Session) -> None:
    if session.exec(select(School)).first():
        return

    schools = [

        # ── 1. UNIS Hanoi ──────────────────────────────────────────────────
        School(
            name="United Nations International School Hanoi",
            slug="unis-hanoi",
            curriculum="IB PYP / MYP / Diploma",
            tuition_range="$15,000 – $35,000",
            district="Tay Ho",
            image_url=_img(0),
            summary="The flagship IB school in Hanoi — best for globally mobile families seeking full IB continuity from nursery to graduation.",
            accreditation="CIS, NEASC, IBO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.unishanoi.org",
            founded_year="1988",
            total_students="~1,600",
            class_size_max="22",
            address="G9 Ciputra, Phu Thuong Ward, Tay Ho, Hanoi",
            facilities="Olympic swimming pool|Sports complex|Black box theatre|Science labs|Makerspace|Library|Counselling centre",
            pros="Full IB continuum from nursery to Diploma|60+ nationalities — most diverse student body in Hanoi|Strong university counselling (95%+ first-choice offers)|Beautiful lakeside campus",
            cons="Among the highest fees in Hanoi|Long waitlists for popular year groups|Tay Ho location tough for families south of the city",
            university_pathways="IB Diploma → strong UK, US, Canadian and Australian placements. Historically 95%+ receive first-choice offer.",
            admissions_timeline="October: Application opens|January: Early decision deadline|March: Rolling admissions continue|May: Final offers sent|August: New student orientation",
            required_documents="Completed application form|Birth certificate|Latest two years school reports|Teacher recommendation letters|Medical and vaccination records|Passport copy",
            faq_questions="Is UNIS only for UN families?|What scholarships does UNIS offer?|How competitive is Grade 6 entry?|Does UNIS have an ELL programme?|What extracurriculars are available?",
            faq_answers="No — UNIS is open to all nationalities. It was founded for the international community and welcomes children from all backgrounds.|UNIS offers a small number of merit-based scholarships for Grade 9 entry each year. Contact admissions directly.|Grade 6 (MYP entry) is competitive. Apply early and submit strong academic records.|Yes — an English Language Learning programme supports non-native speakers across all year groups.|80+ clubs including Model UN, robotics, 30+ sports teams, and performing arts.",
        ),

        # ── 2. BIS Hanoi ───────────────────────────────────────────────────
        School(
            name="British International School Hanoi",
            slug="bis-hanoi",
            curriculum="British National Curriculum + IGCSE + IB Diploma",
            tuition_range="$18,000 – $32,000",
            district="Long Bien",
            image_url=_img(1),
            summary="Strong UK pathway with dual exit: A-Level track or IB Diploma. Popular with British and EU families.",
            accreditation="BSO, Ofsted-inspected, IBO (Diploma)",
            language_of_instruction="English",
            age_range="2–18",
            website_url="https://www.bishanoi.com",
            founded_year="1997",
            total_students="~1,200",
            class_size_max="20",
            address="Vinhomes Riverside, Long Bien, Hanoi",
            facilities="25m swimming pool|Multi-sport AstroTurf|Performing arts centre|STEAM labs|Sixth-form centre|Early years outdoor areas",
            pros="Rigorous British curriculum recognised by top UK universities|Dual exit pathway (A-Levels or IB Diploma)|Vinhomes campus is safe, leafy, and child-friendly|Strong pastoral care",
            cons="Long Bien is far from Tay Ho and central expat areas|British curriculum less well-known to US/French university admissions teams|Smaller community than UNIS",
            university_pathways="IGCSE → A-Levels or IB Diploma → Russell Group / Oxbridge; US and Australian applications also supported.",
            admissions_timeline="September: Applications open|November: Scholarship priority deadline|February: Main admissions round|April: Final offers|August: Welcome week",
            required_documents="Application form|Passport copy|Last two years school reports|Head teacher reference|Medical records|Proof of address",
            faq_questions="Can my child join mid-year?|Is there a sibling discount?|How does the A-Level vs IB choice work?|What EAL support is available?|What is the university placement record?",
            faq_answers="Yes — BIS accepts mid-year applications subject to space. Submit recent school reports to admissions for an initial assessment.|BIS offers 10% off the second child's tuition for families with two or more enrolled children.|Students choose A-Levels or IB Diploma at the start of Year 12. A guidance programme helps families decide by Year 10.|An EAL programme supports students from beginner to advanced levels across all year groups.|90%+ of leavers receive first- or second-choice university offers, including several Oxbridge and Ivy League placements each year.",
        ),

        # ── 3. Concordia ───────────────────────────────────────────────────
        School(
            name="Concordia International School Hanoi",
            slug="concordia-hanoi",
            curriculum="US Common Core + Advanced Placement (AP)",
            tuition_range="$14,000 – $28,000",
            district="Long Bien",
            image_url=_img(2),
            summary="Top choice for US college-bound families. Rigorous AP programme with strong results and smaller class sizes.",
            accreditation="WASC, ACSI, College Board (AP)",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.concordiahanoi.org",
            founded_year="1999",
            total_students="~800",
            class_size_max="18",
            address="Vinhomes Riverside, Long Bien, Hanoi",
            facilities="Gymnasium|Swimming pool|Art studios|Science labs|Chapel|Sports fields",
            pros="Strong AP programme — 18 AP courses offered|Smaller class sizes (avg 8:1 ratio)|Christian values community for faith-based families|Competitive tuition relative to comparable schools",
            cons="Christian orientation may not suit all families|Smaller extracurricular range vs larger schools|US curriculum less recognised by UK/European universities",
            university_pathways="AP → US liberal arts colleges and state universities. Growing placements in Canada and Australia.",
            admissions_timeline="October: Applications open|December: Early deadline|March: Rolling admissions|May: Placement confirmation|August: New student welcome week",
            required_documents="Application and personal statement|Passport and birth certificate|Last two years transcripts|Two teacher references|Medical and immunisation records",
            faq_questions="Is Concordia only for Christian families?|How many AP courses are offered?|Are merit scholarships available?|What is the student-teacher ratio?|Does Concordia support ESL students?",
            faq_answers="Concordia welcomes students of all faiths. Chapel services are held, but participation is respectful and non-compulsory for non-Christian students.|18 AP courses across STEM, humanities, and arts — one of the widest AP selections in Hanoi.|Merit scholarships for Grade 9 and Grade 11 entry. Award value: $2,000–$5,000 per year, renewable.|Average 8:1 student-teacher ratio, enabling close academic support.|ESL support from Kindergarten through Grade 12 with pull-out and in-class support models.",
        ),

        # ── 4. HIS ─────────────────────────────────────────────────────────
        School(
            name="Hanoi International School",
            slug="hanoi-international-school",
            curriculum="IB PYP / MYP / Diploma",
            tuition_range="$12,000 – $25,000",
            district="Dong Da",
            image_url=_img(3),
            summary="Central location with competitive IB fees. Popular with long-term expat families who value a tight-knit community.",
            accreditation="CIS, IBO",
            language_of_instruction="English",
            age_range="5–18",
            website_url="https://www.hisvietnam.com",
            founded_year="1994",
            total_students="~500",
            class_size_max="20",
            address="1 Giang Vo Street, Dong Da, Hanoi",
            facilities="Library|Science labs|Art and music rooms|Sports hall|Pool access via partner facility",
            pros="Most central location — easy from Ba Dinh, Hoan Kiem, Dong Da|Full IB at a significantly lower price than UNIS|Smaller community fosters strong parent network|Strong Vietnamese culture integration",
            cons="Smaller campus — fewer on-site sports facilities than larger schools|Less international diversity than UNIS or BIS|No early years programme (starts Grade 1)",
            university_pathways="IB Diploma with support for UK, US, Australian, and Vietnamese university applications.",
            admissions_timeline="September: Open house and applications begin|January: Rolling admissions|April: Final year group confirmations|August: Orientation day",
            required_documents="Application form|Passport copy|School reports (last 2 years)|Immunisation records|Teacher recommendation",
            faq_questions="Does HIS have an early years programme?|Is Vietnamese language taught?|How do class sizes compare?|What makes HIS different from UNIS?|Is transport available?",
            faq_answers="HIS starts from Grade 1 (age 5–6). For nursery/Kindergarten, consider UNIS or BIS.|Vietnamese language and culture is core curriculum from Grade 1 — popular with families planning a longer stay.|Average 16–18 students — smaller than most Hanoi international schools.|HIS is more affordable and centrally located. UNIS has superior facilities and diversity. Both offer full IB.|HIS partners with a private bus service covering most Hanoi districts at additional cost.",
        ),

        # ── 5. Lycée Yersin ───────────────────────────────────────────────
        School(
            name="Lycée Français Alexandre Yersin",
            slug="lycee-francais-hanoi",
            curriculum="French National Curriculum + IB Diploma",
            tuition_range="$8,000 – $20,000",
            district="Dong Da",
            image_url=_img(4),
            summary="The top choice for French-speaking families. Bilingual French-English with the most affordable fees for the quality offered.",
            accreditation="AEFE (French Ministry of Education), IBO",
            language_of_instruction="French (primary) + English",
            age_range="3–18",
            website_url="https://www.lyceeyersin.com",
            founded_year="1994",
            total_students="~700",
            class_size_max="25",
            address="2A Nguyen Gia Thieu, Dong Da, Hanoi",
            facilities="Gymnasium|Library|Science labs|Art rooms|Canteen|Outdoor play areas",
            pros="Most affordable international school for the quality offered|Bilingual French-English programme|Rigorous French national curriculum|AEFE accreditation recognised globally",
            cons="Primary instruction in French — difficult entry for non-French speakers|English proficiency of graduates can lag English-medium schools|Smaller campus with limited sports facilities",
            university_pathways="Baccalauréat → French grandes écoles; IB Diploma track for senior students → UK, US, Australian universities.",
            admissions_timeline="October: Applications open|February: Language assessment for non-francophone applicants|April: Placement offers|June: Enrolment confirmation|September: School year begins",
            required_documents="Application form|Passport copy|School reports (French or translated)|French language assessment (non-native speakers)|Vaccination record",
            faq_questions="Can non-French-speaking children join?|Is there an English-medium track?|What are AEFE scholarships?|What is the Baccalauréat worth internationally?|What is the school community like?",
            faq_answers="Non-French speakers are accepted but complete a language assessment. An immersion programme supports beginners — expect a challenging first year.|English is taught as a second language throughout; senior students can choose the French Bac or IB Diploma (taught in English).|French government scholarships are available to French nationals through the AEFE network, covering up to 100% of tuition based on financial need.|The French Baccalauréat is recognised by universities across Europe, North America, and Australia — equivalent or superior to A-Levels at most UK universities.|A large Vietnamese-French student body alongside expats creates a uniquely local international atmosphere that many families value highly.",
        ),

        # ── 6. Brighton College Vietnam ───────────────────────────────────
        School(
            name="Brighton College Vietnam",
            slug="brighton-college-vietnam",
            curriculum="British Independent School Curriculum + A-Level + IB Diploma",
            tuition_range="$22,000 – $45,000",
            district="Nam Tu Liem",
            image_url=_img(5),
            summary="Premium British independent school brand. Rigorous academics, outstanding co-curricular life, and exceptional pastoral care.",
            accreditation="ISI (Independent Schools Inspectorate), IBO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.brightoncollege.edu.vn",
            founded_year="2016",
            total_students="~800",
            class_size_max="18",
            address="My Dinh, Nam Tu Liem, Hanoi",
            facilities="Performing arts theatre|Olympic pool|STEM innovation centre|Sports complex|Boarding facilities|Library and media centre",
            pros="Prestigious UK independent school name and curriculum|Exceptionally broad extracurricular programme|Dual exit: A-Level or IB Diploma|Strong university counselling from Year 9",
            cons="Among the highest fees in Hanoi|Nam Tu Liem location far from northern expat clusters|Selective admissions may not suit all children",
            university_pathways="A-Level or IB Diploma → Oxbridge, Russell Group, Ivy League. Dedicated university counselling from Year 9.",
            admissions_timeline="September: Applications open|December: Scholarship assessment deadline|February: Main round offers|May: Enrolment confirmation",
            required_documents="Application form|Academic transcripts (last 2 years)|Entrance assessment|Head teacher reference|Passport|Medical records",
            faq_questions="Is Brighton College Vietnam affiliated with Brighton College UK?|What boarding options exist?|Are there music or arts scholarships?|How selective is admissions?|What is the A-Level vs IB choice process?",
            faq_answers="Yes — Brighton College Vietnam operates under the Brighton College UK umbrella, sharing curriculum philosophy and quality standards.|Day school with extended day options. Some boarding-style arrangements may be available — contact admissions.|Academic, music, sport, and all-round scholarships are available at Year 7 and Year 12 entry.|Entry assessments test core academic ability. The school admits students with strong academic foundations and genuine curiosity.|Students make the A-Level or IB Diploma decision in Year 11 with guidance from the Head of Sixth Form and university counsellors.",
        ),

        # ── 7. Reigate Grammar School Vietnam ─────────────────────────────
        School(
            name="Reigate Grammar School Vietnam",
            slug="reigate-grammar-vietnam",
            curriculum="British National Curriculum + IGCSE + A-Level",
            tuition_range="$20,000 – $36,000",
            district="Ha Dong",
            image_url=_img(6),
            summary="UK independent school heritage, full A-Level pathway, and strong arts programme at Gamuda Gardens campus.",
            accreditation="ISI, BSO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.rgs.edu.vn",
            founded_year="2018",
            total_students="~600",
            class_size_max="18",
            address="Gamuda Gardens, Hoang Mai / Ha Dong, Hanoi",
            facilities="Sports hall|Performing arts centre|Science labs|Swimming pool|Library|Art studios",
            pros="Prestigious UK independent school name|Full A-Level (not just IGCSE) — relatively rare in Hanoi|Strong arts and music provision|Gamuda Gardens campus is modern and well-maintained",
            cons="Ha Dong / Gamuda Gardens is a long commute from northern and central Hanoi|Relatively newer school — building track record|A-Level rather than IB may limit non-UK university applications",
            university_pathways="IGCSE → A-Level → UK universities (strong Russell Group focus). US and European applications supported.",
            admissions_timeline="September: Applications open|January: Scholarship round|March: Rolling admissions|June: Final confirmation|August: Welcome week",
            required_documents="Application form|Two years of school reports|Head teacher reference|Entrance assessment (English and Maths)|Passport and medical records",
            faq_questions="Is RGS Vietnam the same as RGS UK?|Are there scholarships at Year 7 and Year 12?|How is the Ha Dong location for commuting?|Does RGS offer an IB option?|What university destinations do students achieve?",
            faq_answers="RGS Vietnam operates under licence from Reigate Grammar School UK and shares its curriculum standards and ethos.|Academic and co-curricular scholarships are offered at Year 7 and Year 12 entry. Awards cover 10–30% of tuition fees.|Ha Dong is about 25–40 minutes from Tay Ho and 20 minutes from Hoan Kiem. The school runs a bus service covering key areas.|RGS Vietnam offers A-Levels rather than the IB Diploma. Students seeking IB should consider UNIS, BIS, or Concordia.|Graduates achieve strong UK university placements including Russell Group universities.",
        ),

        # ── 8. Rugby School Hanoi ─────────────────────────────────────────
        School(
            name="Rugby School Hanoi",
            slug="rugby-school-hanoi",
            curriculum="British National Curriculum + IGCSE + A-Level",
            tuition_range="$25,000 – $42,000",
            district="Tay Ho",
            image_url=_img(7),
            summary="One of Britain's oldest school brands, now in Hanoi. Outstanding boarding culture, sport, and A-Level provision.",
            accreditation="ISI, BSO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.rugbyschoolhanoi.com",
            founded_year="2017",
            total_students="~500",
            class_size_max="16",
            address="Tay Ho, Hanoi",
            facilities="Sports oval|Indoor sports hall|Theatre|STEM labs|Boarding house|Swimming pool|Music centre",
            pros="Famous UK independent school heritage|Exceptional sports programme (Rugby School originated the sport)|Strong boarding community for expat families|Very small class sizes",
            cons="Premium fees at the top of the Hanoi market|A-Level rather than IB Diploma|Limited class sizes mean occasional waitlists",
            university_pathways="IGCSE → A-Level → UK Russell Group and Oxbridge. History of Oxbridge placements at Rugby UK reflected in Vietnam branch.",
            admissions_timeline="October: Applications open|December: Scholarship deadline|February: Main admissions|May: Final offers|August: School begins",
            required_documents="Application and reference|Academic transcripts|Entrance assessment|Passport and medical documents",
            faq_questions="Does Rugby School Hanoi offer boarding?|What makes Rugby different from other British schools?|Are there sports scholarships?|How does A-Level preparation compare to IB?|Is the school suitable for non-British children?",
            faq_answers="Yes — Rugby School Hanoi offers a boarding programme suited to expat families on rotation or travelling parents.|Rugby combines world-class sport with strong academics and a distinctive house system that builds community and leadership.|Sport, music, and academic scholarships are available at Year 7 and Year 12 entry.|A-Levels are widely regarded as more focused and rigorous for UK university applications. For global mobility and multiple university systems, IB may be preferable.|Absolutely — the international student body includes children from across Asia, Europe, and the Americas.",
        ),

        # ── 9. Dwight School Hanoi ────────────────────────────────────────
        School(
            name="Dwight School Hanoi",
            slug="dwight-school-hanoi",
            curriculum="IB PYP / MYP / Diploma",
            tuition_range="$15,000 – $30,000",
            district="Cau Giay",
            image_url=_img(8),
            summary="IB World School focused on spark-based learning — identifying and nurturing each child's unique talents.",
            accreditation="IBO, CIS candidate",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.dwighthanoi.edu.vn",
            founded_year="2014",
            total_students="~400",
            class_size_max="20",
            address="Cau Giay, Hanoi",
            facilities="SPARK Centre (innovation lab)|Arts studios|Sports hall|Library|Science labs",
            pros="Distinctive 'spark' philosophy — strong focus on individual passions|Full IB continuum|Part of the global Dwight Schools network|Cau Giay location accessible from many parts of Hanoi",
            cons="Newer school still building its track record|Smaller campus than UNIS|Less established parent alumni network",
            university_pathways="IB Diploma → global university applications. Dwight Schools globally have strong US and UK placement records.",
            admissions_timeline="Year-round rolling admissions|January: Scholarship priority deadline|August: New student orientation",
            required_documents="Application form|School reports (2 years)|Teacher reference|Passport|Medical records",
            faq_questions="What is the 'spark' philosophy?|How does Dwight compare to UNIS for the IB?|Are there scholarships?|What is the school's nationality mix?|Is there an early years programme?",
            faq_answers="Dwight's spark philosophy holds that every child has a unique gift. Teachers are trained to identify and nurture individual passions alongside the IB curriculum.|Both offer full IB. UNIS is larger and more established. Dwight offers a more personalised, innovative approach with smaller class sizes.|Need-based and merit bursaries are available. Contact admissions for current awards.|A diverse international community, with strong Korean, Japanese, and Western European representation.|Yes — Dwight offers IB PYP from age 3, with a nurturing early years programme.",
        ),

        # ── 10. The International School @ ParkCity ───────────────────────
        School(
            name="The International School @ ParkCity Hanoi",
            slug="parkcity-hanoi",
            curriculum="Cambridge Primary / Lower Secondary + IGCSE + IB Diploma",
            tuition_range="$14,000 – $26,000",
            district="Ha Dong",
            image_url=_img(9),
            summary="Modern campus at ParkCity Hanoi. Cambridge framework through IGCSE, then IB Diploma — giving students two of the world's most recognised qualifications.",
            accreditation="Cambridge International, IBO",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.isph.edu.vn",
            founded_year="2013",
            total_students="~600",
            class_size_max="20",
            address="ParkCity Hanoi, Ha Dong",
            facilities="Indoor swimming pool|Sports hall|STEAM labs|Library|Performing arts studio|Campus gardens",
            pros="Cambridge + IB dual pathway is excellent preparation for global universities|Modern, purpose-built campus|Green ParkCity environment — safe and pleasant|More affordable than top-tier UK-brand schools",
            cons="Ha Dong location suits southern Hanoi residents — long commute from north|Newer school building track record|Smaller sixth form",
            university_pathways="IGCSE → IB Diploma → UK, US, Australian, and Asian universities.",
            admissions_timeline="September: Applications open|January: Scholarship deadline|March: Rolling admissions|May: Final offers|August: Induction week",
            required_documents="Application form|School reports|Teacher reference|Language assessment if applicable|Passport and medical records",
            faq_questions="Is ParkCity only for residents of the ParkCity estate?|Does the school offer Vietnamese language?|What is the after-school activity programme like?|Are there scholarship opportunities?|How diverse is the student body?",
            faq_answers="No — the school is open to all families. Many students commute from different parts of Hanoi.|Vietnamese language and culture is offered as an elective and is integrated into the international programme.|A broad after-school activity programme includes STEAM clubs, sports, music, and arts — running until 5pm on most days.|Merit scholarships are available at Year 7 and IB Diploma entry. Contact admissions for the current cycle.|A genuinely international community with strong Korean, Vietnamese, and Western European representation.",
        ),

        # ── 11. True North International School ──────────────────────────
        School(
            name="True North International School",
            slug="true-north-hanoi",
            curriculum="Canadian Curriculum + IB Diploma",
            tuition_range="$12,000 – $24,000",
            district="Tay Ho",
            image_url=_img(10),
            summary="Canadian-accredited school with a warm, inclusive culture and IB Diploma in senior years. Ideal for families planning North American university applications.",
            accreditation="BC Ministry of Education (Canada), IBO",
            language_of_instruction="English",
            age_range="4–18",
            website_url="https://www.truenorth.edu.vn",
            founded_year="2012",
            total_students="~350",
            class_size_max="22",
            address="Tay Ho, Hanoi",
            facilities="Science labs|Library|Sports hall|Arts room|Outdoor courts",
            pros="Canadian curriculum highly valued for North American university applications|IB Diploma option in senior years|Welcoming, inclusive community|Tay Ho location suits expat families in the north",
            cons="Smaller school — limited range of extracurriculars|Building track record vs established schools|Fewer specialist facilities than larger campuses",
            university_pathways="Canadian diploma + IB Diploma → Canadian, US, UK, and Australian universities. BC credential widely recognised.",
            admissions_timeline="Year-round rolling admissions|January: Priority scholarship deadline|August: New student orientation",
            required_documents="Application form|Transcripts (2 years)|Teacher reference|Passport|Medical records",
            faq_questions="What is the BC (British Columbia) curriculum?|Does True North offer IB for all year groups?|Are there scholarships?|Is the school affiliated with a Canadian school?|How large are the classes?",
            faq_answers="BC curriculum follows British Columbia's Ministry of Education framework — one of Canada's most rigorous provincial programmes, recognised by universities worldwide.|The BC curriculum runs from Kindergarten through Grade 11. Grade 12 students choose between the BC diploma and the IB Diploma.|Need-based and merit scholarships are available. Enquire with admissions for the current cycle.|True North is accredited by the BC Ministry of Education and may have affiliate relationships with Canadian institutions — confirm with the school.|Average class sizes of 18–22 students, with small group support available.",
        ),

        # ── 12. BVIS Hanoi ────────────────────────────────────────────────
        School(
            name="British Vietnamese International School Hanoi",
            slug="bvis-hanoi",
            curriculum="British National Curriculum + IGCSE + IB Diploma",
            tuition_range="$12,000 – $24,000",
            district="Long Bien",
            image_url=_img(11),
            summary="Affordable British curriculum school with a large Vietnamese-international student community. Solid academics, multiple campuses across Hanoi.",
            accreditation="BSO, Nord Anglia Education",
            language_of_instruction="English",
            age_range="2–18",
            website_url="https://www.bvishanoi.com",
            founded_year="2005",
            total_students="~1,500",
            class_size_max="22",
            address="Royal City & Van Phuc, Hanoi (multiple campuses)",
            facilities="Swimming pool|Sports hall|Science labs|Library|Arts rooms|EYC outdoor play area",
            pros="Nord Anglia network — global curriculum development partnerships|Multiple campuses — flexible location options|More affordable than BIS or UNIS|Large, established community",
            cons="Larger class sizes than premium schools|Quality can vary slightly between campuses|Less selective admissions — wider academic ability range",
            university_pathways="IGCSE → A-Levels or IB Diploma → UK and global universities via Nord Anglia network support.",
            admissions_timeline="Year-round rolling admissions|October: Scholarship priority round|March: Main intake confirmations",
            required_documents="Application form|School reports|Teacher reference|Passport|Medical records",
            faq_questions="Is BVIS part of the Nord Anglia group?|Which campus should I choose?|What IB or A-Level options exist?|Is there an EAL programme?|What extracurriculars are offered?",
            faq_answers="Yes — BVIS Hanoi is part of the Nord Anglia Education network, which connects over 80 schools globally.|The Van Phuc campus suits families in Long Bien and eastern Hanoi; the Royal City campus is central and good for Ha Dong or Dong Da residents.|IB Diploma is available from Year 12 at senior campuses. Some campuses offer A-Level preparation — confirm with admissions.|A comprehensive EAL programme supports students at all levels, with pull-out and in-class support models.|A broad range including sports, arts, music, STEM clubs, and community service activities.",
        ),

        # ── 13. Singapore International School Ciputra ───────────────────
        School(
            name="Singapore International School (Ciputra)",
            slug="sis-ciputra",
            curriculum="Cambridge Primary + IGCSE + IB Diploma",
            tuition_range="$12,000 – $22,000",
            district="Tay Ho",
            image_url=_img(12),
            summary="Well-established Singapore-model school at Ciputra. Cambridge pathway through IGCSE, then IB Diploma — excellent for Singapore / ASEAN university pathways.",
            accreditation="Cambridge International, IBO, MOE Singapore-affiliated",
            language_of_instruction="English (with Mandarin elective)",
            age_range="3–18",
            website_url="https://www.sisvietnam.com",
            founded_year="2004",
            total_students="~900",
            class_size_max="22",
            address="Ciputra, Tay Ho, Hanoi",
            facilities="Swimming pool|Sports courts|STEM labs|Library|Canteen|Early years playground",
            pros="Strong Asian and Western university placement record|Mandarin as a second language option|Located in Ciputra — very convenient for Tay Ho expat families|More affordable than UK independent schools",
            cons="Larger class sizes than premium schools|Ciputra location can mean traffic congestion at pick-up|Some families find the Singapore model more exam-focused than IB",
            university_pathways="IGCSE → IB Diploma → UK, US, Australian, and Singapore/ASEAN universities.",
            admissions_timeline="Year-round rolling admissions|January: Scholarship priority|August: New student orientation",
            required_documents="Application form|School reports|Teacher reference|Passport|Language assessment if applicable",
            faq_questions="How does SIS differ from UNIS?|Is Mandarin available for beginners?|Are there scholarships?|What is the IB Diploma pass rate?|Does the school have an early years programme?",
            faq_answers="SIS follows Cambridge Primary to IGCSE then IB Diploma. UNIS is full IB from nursery. SIS suits families prioritising Cambridge qualifications in the early years.|Mandarin is offered as a second language from Primary — both heritage and beginner pathways are available.|Merit and need-based scholarships are available. Contact admissions for current awards.|IB Diploma pass rates are competitive — typically above the global average. Check the school's most recent results.|Yes — SIS offers a full early years programme from age 3.",
        ),

        # ── 14. SIS Gamuda Gardens ────────────────────────────────────────
        School(
            name="Singapore International School (Gamuda Gardens)",
            slug="sis-gamuda",
            curriculum="Cambridge Primary + IGCSE + IB Diploma",
            tuition_range="$11,000 – $21,000",
            district="Ha Dong",
            image_url=_img(13),
            summary="Modern SIS campus at Gamuda Gardens — same strong Cambridge + IB pathway as Ciputra but in the south of the city.",
            accreditation="Cambridge International, IBO",
            language_of_instruction="English (with Mandarin elective)",
            age_range="3–18",
            website_url="https://www.sisvietnam.com/gamuda",
            founded_year="2018",
            total_students="~500",
            class_size_max="22",
            address="Gamuda Gardens, Hoang Mai / Ha Dong, Hanoi",
            facilities="Swimming pool|Sports hall|STEM labs|Library|Early years outdoor area|Canteen",
            pros="Slightly more affordable than Ciputra campus|Modern purpose-built facilities|Gamuda Gardens is a green, safe residential environment|Same SIS curriculum and quality standards",
            cons="Gamuda / Ha Dong is far from Tay Ho and northern Hanoi|Newer campus — smaller community than Ciputra|Less established alumni network",
            university_pathways="IGCSE → IB Diploma → UK, US, Australian, and Singapore/ASEAN universities.",
            admissions_timeline="Year-round admissions|January: Scholarship priority|August: Orientation",
            required_documents="Application form|School reports|Teacher reference|Passport|Medical records",
            faq_questions="What is the difference between SIS Ciputra and SIS Gamuda?|Does the Gamuda campus share teachers with Ciputra?|Are there scholarships?|What age groups are at the Gamuda campus?|How far is Gamuda Gardens from the city centre?",
            faq_answers="Both follow the same Cambridge + IB pathway under the SIS brand. Ciputra is more established; Gamuda Gardens is newer, slightly cheaper, and better for southern Hanoi families.|The two campuses share curriculum leadership and professional development but have separate teaching staff and management.|Yes — contact admissions for the current scholarship cycle.|Full school from Early Years (age 3) through Year 13 (IB Diploma).|Gamuda Gardens is approximately 15–20 minutes from the Old Quarter and 25–35 minutes from Tay Ho in normal traffic.",
        ),

        # ── 15. SIS Van Phuc ──────────────────────────────────────────────
        School(
            name="Singapore International School (Van Phuc)",
            slug="sis-van-phuc",
            curriculum="Cambridge Primary + IGCSE + IB Diploma",
            tuition_range="$10,000 – $20,000",
            district="Long Bien",
            image_url=_img(14),
            summary="The original SIS campus in Hanoi, well-loved by families in Long Bien and the eastern districts.",
            accreditation="Cambridge International, IBO",
            language_of_instruction="English (with Mandarin elective)",
            age_range="3–18",
            website_url="https://www.sisvietnam.com/van-phuc",
            founded_year="2004",
            total_students="~700",
            class_size_max="24",
            address="Vinhomes Riverside / Van Phuc, Long Bien, Hanoi",
            facilities="Swimming pool|Sports courts|Library|Science labs|Canteen",
            pros="Established community with strong parent network|Long Bien location convenient for Vinhomes and eastern Hanoi|Slightly lower fees than Ciputra campus|Cambridge + IB pathway",
            cons="Older facilities compared to newer SIS campuses|Larger class sizes at some year groups|Long Bien is far from Tay Ho and western expat clusters",
            university_pathways="IGCSE → IB Diploma → UK, US, Australian, and Singapore/ASEAN universities.",
            admissions_timeline="Year-round rolling admissions|January: Scholarship priority|August: New student orientation",
            required_documents="Application form|School reports|Teacher reference|Passport|Medical records",
            faq_questions="Is Van Phuc the oldest SIS campus?|Are facilities being upgraded?|How does Long Bien compare to Ciputra for expat living?|Are there scholarships?|What is the IB Diploma pass rate?",
            faq_answers="Yes — Van Phuc was the first SIS campus to open in Hanoi and has the longest established community.|SIS regularly invests in facilities upgrades — check with admissions for the latest campus developments.|Long Bien has grown significantly as an expat area, especially around Vinhomes Riverside. It suits families working east of Hoan Kiem.|Yes — merit and need-based scholarships available. Enquire with admissions.|IB Diploma pass rates typically above the global average. Check the school's published annual results.",
        ),

        # ── 16. Brendon Primary ───────────────────────────────────────────
        School(
            name="Brendon International Primary School",
            slug="brendon-primary",
            curriculum="British National Curriculum (Primary only)",
            tuition_range="$8,000 – $14,000",
            district="Tay Ho",
            image_url=_img(0),
            summary="Intimate British primary school focused exclusively on EYFS and Key Stage 1–2. High parent satisfaction scores and close teacher-family relationships.",
            accreditation="BSO candidate",
            language_of_instruction="English",
            age_range="3–11",
            website_url="https://www.brendon.edu.vn",
            founded_year="2011",
            total_students="~200",
            class_size_max="18",
            address="Tay Ho, Hanoi",
            facilities="Early years outdoor areas|Library|Sports hall|Art room|Music room",
            pros="Small, nurturing community — every child known by name|British EYFS and primary curriculum at competitive fees|Tay Ho location very convenient for expat families|Strong transition support to secondary schools",
            cons="Primary only — families must move school at age 11|Smaller range of specialist subjects and facilities|Limited extracurricular clubs vs larger schools",
            university_pathways="N/A (Primary only). Strong transition guidance to BIS, UNIS, Concordia and other Hanoi secondary schools.",
            admissions_timeline="Year-round rolling admissions|August: Main intake|January: Mid-year places available",
            required_documents="Application form|Previous nursery/school report if applicable|Passport|Vaccination records",
            faq_questions="What age does Brendon go up to?|How does Brendon support the transition to secondary school?|Is the school suitable for non-native English speakers?|Are there after-school clubs?|What makes Brendon different from larger primary schools?",
            faq_answers="Brendon is a primary school only — it covers ages 3 to 11 (EYFS through Year 6). Families plan secondary transition from Year 4 onwards.|A dedicated secondary transition programme supports students and parents in applying to UNIS, BIS, Concordia, and other secondary schools.|An EAL support programme helps non-native English speakers settle in and develop language skills alongside the curriculum.|A range of after-school clubs including sports, art, music, and STEM activities run until 5pm on weekdays.|The small size creates an extraordinarily close community — teachers know every family by name, and pastoral care is exceptional.",
        ),

        # ── 17. Hanoi Academy ─────────────────────────────────────────────
        School(
            name="Hanoi Academy International Bilingual School",
            slug="hanoi-academy",
            curriculum="Vietnamese Ministry + Cambridge International + IGCSE",
            tuition_range="$8,000 – $16,000",
            district="Nam Tu Liem",
            image_url=_img(1),
            summary="Large bilingual school combining Vietnamese Ministry of Education requirements with Cambridge International. Excellent choice for families planning a long stay in Vietnam.",
            accreditation="Cambridge International, MOET (Vietnam)",
            language_of_instruction="Vietnamese + English",
            age_range="3–18",
            website_url="https://www.hanoiacademy.edu.vn",
            founded_year="2010",
            total_students="~2,000",
            class_size_max="25",
            address="Nam Tu Liem, Hanoi",
            facilities="Large sports complex|Swimming pool|Science labs|Library|Arts centre|Canteen",
            pros="Deep Vietnamese language and culture alongside Cambridge curriculum|Competitive fees for size and facilities|Large campus with excellent sports facilities|Very well-regarded among Vietnamese-international families",
            cons="Larger class sizes than premium international schools|Bilingual instruction can be challenging for non-Vietnamese speakers initially|Less suited for families planning to leave Vietnam in 1–2 years",
            university_pathways="IGCSE and Cambridge pathway → UK, Australian, and Vietnamese universities. Some students complete IELTS for international applications.",
            admissions_timeline="September: Applications open for following year|March: Final places confirmed|August: Orientation",
            required_documents="Application form|School reports|Vietnamese language assessment (optional for non-Vietnamese)|Passport|Vaccination records",
            faq_questions="Is Vietnamese language mandatory?|How is the Cambridge curriculum integrated with Vietnamese MOET?|Are there scholarships?|Is the school suitable for a child arriving with no Vietnamese?|What sports facilities are available?",
            faq_answers="Vietnamese is a core subject for all students. For non-Vietnamese speakers, a language support programme helps students reach a working level over 1–2 years.|MOET subjects (Vietnamese history, civic education, Vietnamese literature) are taught in Vietnamese; Cambridge subjects in English. Students follow both curricula in parallel.|Merit and need-based scholarships are available for both Vietnamese and international students.|Children with no Vietnamese can join — the school has experience supporting non-native speakers. However, this school is best suited to families planning to stay long-term.|A large multi-sport complex includes football pitches, badminton courts, basketball courts, and an indoor swimming pool.",
        ),

        # ── 18. GIS Hanoi ─────────────────────────────────────────────────
        School(
            name="Global International School Hanoi",
            slug="gis-hanoi",
            curriculum="British National Curriculum + IGCSE + A-Level",
            tuition_range="$8,000 – $18,000",
            district="Cau Giay",
            image_url=_img(2),
            summary="Growing international school network in Hanoi offering British curriculum at accessible fees. Multiple campuses across the city.",
            accreditation="Cambridge International, British Council partner",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.gis.edu.vn",
            founded_year="2008",
            total_students="~1,200",
            class_size_max="22",
            address="Multiple campuses — Cau Giay, Tay Ho, Ha Dong",
            facilities="Sports hall|Science labs|Library|Swimming pool (select campuses)|Arts rooms",
            pros="Multiple campus locations across Hanoi|British curriculum at competitive fees|Growing reputation — improving year on year|Flexible mid-year admissions",
            cons="Quality can vary between campuses — visit before choosing|Less selective than top-tier schools|Facilities vary by campus",
            university_pathways="IGCSE → A-Level → UK and international university applications.",
            admissions_timeline="Year-round rolling admissions across campuses|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records",
            faq_questions="Which GIS campus is best?|Does GIS offer IB?|Are there scholarships?|How does GIS compare to BIS?|Can students transfer between campuses?",
            faq_answers="Each campus has slightly different strengths — visit all options in your area before deciding. The Cau Giay campus is well-regarded.|GIS primarily follows British curriculum with A-Levels. IB Diploma is not currently offered — families seeking IB should consider SIS, UNIS, or BIS.|Merit scholarships and sibling discounts are available. Contact your preferred campus.|BIS is more established, more selective, and has higher fees. GIS offers a more affordable British curriculum alternative.|Yes — transferring between GIS campuses is generally straightforward, subject to space availability.",
        ),

        # ── 19. The Olympia Schools ───────────────────────────────────────
        School(
            name="The Olympia Schools",
            slug="olympia-schools",
            curriculum="IB PYP / MYP / Diploma + Vietnamese MOET",
            tuition_range="$10,000 – $20,000",
            district="Nam Tu Liem",
            image_url=_img(3),
            summary="Innovative Vietnamese-managed IB school. Strong arts and STEAM focus, bilingual Vietnamese-English, and full IB continuum.",
            accreditation="IBO, MOET (Vietnam)",
            language_of_instruction="English + Vietnamese",
            age_range="3–18",
            website_url="https://www.olympiaschools.edu.vn",
            founded_year="2010",
            total_students="~1,500",
            class_size_max="22",
            address="Nam Tu Liem, Hanoi",
            facilities="Innovation lab|Performing arts centre|Sports complex|Library|Science labs|Swimming pool",
            pros="Full IB continuum from age 3|Strong STEAM and arts integration|Vietnamese management with international standards|Growing university placement track record",
            cons="Vietnamese + IB dual curriculum can be demanding|Not ideal for families planning departure in 1–2 years|Some expat families find the bilingual model challenging initially",
            university_pathways="IB Diploma → international universities. Strong track record of Vietnamese students at US and Australian universities.",
            admissions_timeline="September: Applications open|February: Scholarship round|August: Induction week",
            required_documents="Application|School reports|Teacher reference|Passport|Language assessment",
            faq_questions="Is Olympia a Vietnamese or international school?|How is IB delivered alongside the Vietnamese curriculum?|Are there scholarships?|Is the school suitable for expat children?|What STEAM facilities exist?",
            faq_answers="Olympia is a Vietnamese-managed private school with full IBO authorisation. It bridges both worlds — international standards with Vietnamese cultural integration.|Core IB subjects are taught in English; Vietnamese subjects meet MOET requirements. It requires strong bilingual capacity by secondary school.|Need-based and merit scholarships are available for both Vietnamese and international applicants.|Yes — expat children are welcomed and the school has growing experience supporting non-Vietnamese speakers. Most suited for long-term Hanoi families.|A dedicated Innovation Lab with 3D printers, robotics kits, coding stations, and a maker space. Strong performing arts with a purpose-built theatre.",
        ),

        # ── 20. The Dewey Schools ─────────────────────────────────────────
        School(
            name="The Dewey Schools",
            slug="dewey-schools",
            curriculum="American Common Core + AP + Project-Based Learning",
            tuition_range="$8,000 – $16,000",
            district="Cau Giay",
            image_url=_img(4),
            summary="American-style education with a project-based learning focus. Multiple campuses, accessible fees, and a strong arts programme.",
            accreditation="WASC candidate, College Board (AP)",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.dewey.edu.vn",
            founded_year="2008",
            total_students="~1,000",
            class_size_max="24",
            address="Multiple campuses — Cau Giay, Long Bien, Ha Dong",
            facilities="Science labs|Arts studios|Sports hall|Library|Computer labs|Music rooms",
            pros="Hands-on, project-based American curriculum|Accessible fees for US-style education|Multiple campuses|Strong arts and creativity programme",
            cons="Not WASC-accredited yet — limits US university recognition|Quality uneven across campuses|Less rigorous academic preparation than Concordia for US colleges",
            university_pathways="AP pathway → US and international university applications. Project-based learning portfolio supplements academic record.",
            admissions_timeline="Year-round rolling admissions|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records",
            faq_questions="What is project-based learning?|Does Dewey offer AP courses?|How does Dewey compare to Concordia for US university preparation?|Which campus is recommended?|Are there scholarships?",
            faq_answers="Project-based learning (PBL) organises curriculum around real-world challenges and projects. Students develop critical thinking, collaboration, and creativity alongside core academics.|AP courses are available in senior years. Number of offerings varies by campus — confirm with admissions.|Concordia is the stronger choice for competitive US university applications (WASC-accredited, more rigorous AP programme). Dewey suits families valuing creativity and a more flexible approach.|Visit all campuses in your preferred area before deciding. The Cau Giay and Long Bien campuses are generally well-regarded.|Merit and sibling discounts are available. Enquire with your preferred campus.",
        ),

        # ── 21. Wellspring International Bilingual School ─────────────────
        School(
            name="Wellspring International Bilingual School",
            slug="wellspring-hanoi",
            curriculum="Vietnamese MOET + Cambridge International + IGCSE",
            tuition_range="$5,000 – $12,000",
            district="Long Bien",
            image_url=_img(5),
            summary="Popular bilingual school with strong Vietnamese language integration and Cambridge International endorsement. Best value for families planning a long-term Hanoi stay.",
            accreditation="Cambridge International, MOET",
            language_of_instruction="Vietnamese + English",
            age_range="3–18",
            website_url="https://www.wellspring.edu.vn",
            founded_year="2006",
            total_students="~2,500",
            class_size_max="28",
            address="Long Bien, Hanoi (multiple campuses)",
            facilities="Sports complex|Swimming pool|Library|Science labs|Arts rooms",
            pros="Excellent value for bilingual education|Deep Vietnamese language integration|Strong local reputation — well-regarded by Vietnamese families|Large community with extensive extracurriculars",
            cons="Very large classes at some year groups|Primarily suited to Vietnamese-international families, not pure expat placements|Less suited for families on short-term rotations",
            university_pathways="Cambridge IGCSE → A-Level track or Vietnamese university entrance. A growing number of graduates go to UK, Australian, and US universities.",
            admissions_timeline="Year-round admissions|August: Main intake|January: Mid-year intake",
            required_documents="Application form|School reports|Vaccination records|Passport or ID|Vietnamese language assessment for non-native speakers",
            faq_questions="Is Wellspring primarily for Vietnamese children?|What is the language balance?|Are there scholarships?|Can expat children manage the Vietnamese curriculum?|What are the fees?",
            faq_answers="Wellspring serves a mix of Vietnamese and international families, though the majority are Vietnamese. It is best suited for families intending to stay in Hanoi long-term.|Core international subjects are in English; Vietnamese subjects (literature, history, civic education) are taught in Vietnamese.|Merit scholarships and tuition assistance are available. Contact admissions for current offers.|Expat children with no Vietnamese background can manage — the school has EAL support — but families should be committed to learning Vietnamese.|Fees start from approximately $5,000/year for primary — among the most competitive in Hanoi for Cambridge-endorsed education.",
        ),

        # ── 22. Vietnam-Australia School Hanoi ───────────────────────────
        School(
            name="Vietnam-Australia International School Hanoi",
            slug="vas-hanoi",
            curriculum="Australian Curriculum + Cambridge + IGCSE",
            tuition_range="$8,000 – $18,000",
            district="Ba Dinh",
            image_url=_img(6),
            summary="Large Australian-curriculum school with strong community feel. Popular with Australian expat families and Vietnamese families seeking Western education.",
            accreditation="ACARA (Australian Curriculum), Cambridge International",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.vas.edu.vn",
            founded_year="2000",
            total_students="~2,000",
            class_size_max="25",
            address="Ba Dinh, Hanoi",
            facilities="Sports oval|Swimming pool|Science labs|Library|Performing arts spaces|Canteen",
            pros="Australian curriculum widely recognised for Australian university entry|Large, vibrant community|Central Ba Dinh location|Competitive fees for size and facilities",
            cons="Not ideal for families targeting UK or US universities specifically|Large class sizes at peak year groups|Less selective than premium international schools",
            university_pathways="Australian curriculum + IGCSE → Australian universities (strong), UK and international applications also supported via IELTS.",
            admissions_timeline="Year-round rolling admissions|August: Main intake|January: Additional intake",
            required_documents="Application form|School reports|Passport|Medical records|IELTS/English assessment if applicable",
            faq_questions="Is VAS suitable for non-Australian families?|How does the Australian curriculum compare to British?|Are there scholarships?|What Australian university placements have graduates achieved?|Is Vietnamese language taught?",
            faq_answers="Absolutely — VAS welcomes families of all nationalities. The Australian curriculum is internationally recognised and broad-based.|Both are rigorous Western curricula. The Australian curriculum uses continuous assessment rather than end-of-year exams, which suits many learners. For UK university entry, A-Levels or IB may provide a stronger foundation.|Merit and need-based scholarships are available. Enquire with admissions for the current cycle.|VAS graduates have entered top Australian universities including Melbourne, ANU, UNSW, and Sydney. International university placements are growing.|Yes — Vietnamese language and culture is offered throughout the school as both a subject and a co-curricular activity.",
        ),

        # ── 23. Hanoi Toronto School ──────────────────────────────────────
        School(
            name="Hanoi Toronto School",
            slug="hanoi-toronto-school",
            curriculum="Canadian (Ontario) Curriculum + IB Diploma",
            tuition_range="$10,000 – $20,000",
            district="Tay Ho",
            image_url=_img(7),
            summary="Ontario Ministry of Education curriculum in Hanoi — one of the few genuine Canadian-accredited programmes. IB Diploma in senior years.",
            accreditation="Ontario Ministry of Education (Canada), IBO",
            language_of_instruction="English",
            age_range="4–18",
            website_url="https://www.hanoitoronto.edu.vn",
            founded_year="2015",
            total_students="~300",
            class_size_max="20",
            address="Tay Ho, Hanoi",
            facilities="Science labs|Library|Sports hall|Arts room|Music room",
            pros="Ontario credential widely recognised for Canadian and international university entry|IB Diploma option provides further global recognition|Smaller school — personalised attention|Tay Ho location suits northern expat families",
            cons="Small school — limited specialist subjects and facilities|Building track record|Fewer extracurricular offerings than larger schools",
            university_pathways="Ontario Secondary School Diploma → Canadian universities (strong). IB Diploma → global university applications.",
            admissions_timeline="Year-round rolling admissions|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records|Teacher reference",
            faq_questions="Is the Ontario diploma recognised in Canada?|Does the school have links to Canadian universities?|Are there scholarships?|How large are the classes?|Is the school suitable for non-Canadians?",
            faq_answers="Yes — the Ontario Secondary School Diploma (OSSD) is the primary credential for admission to Canadian universities and is also recognised by universities in the UK, US, and Australia.|The school maintains links with Canadian educational organisations and provides guidance on Canadian university applications.|Need-based and merit bursaries are available. Enquire with admissions.|Classes average 16–20 students — small enough for individualised support.|Absolutely — the school welcomes students of all nationalities. The Ontario curriculum is broad and internationally accessible.",
        ),

        # ── 24. Morning Star International School ─────────────────────────
        School(
            name="Morning Star International School",
            slug="morning-star-hanoi",
            curriculum="American Curriculum + AP",
            tuition_range="$6,000 – $12,000",
            district="Tay Ho",
            image_url=_img(8),
            summary="Christian-values American school. Affordable fees, strong moral education, and caring community — popular with faith-based families across Asia.",
            accreditation="ACSI, College Board (AP)",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.msis.edu.vn",
            founded_year="2004",
            total_students="~400",
            class_size_max="20",
            address="Tay Ho, Hanoi",
            facilities="Chapel|Sports court|Library|Science labs|Arts room",
            pros="Very competitive fees for American curriculum|Strong moral and character education|Caring, close-knit community|AP courses for senior students",
            cons="Christian orientation — services and culture may not suit all families|Less selective than Concordia for competitive US college placement|Smaller facilities",
            university_pathways="AP → US college and university applications. Strong support for Christian liberal arts colleges and broader US institutions.",
            admissions_timeline="Year-round rolling admissions|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records|Statement of faith (optional for non-Christian families)",
            faq_questions="Is Morning Star only for Christian families?|How does it compare to Concordia?|Are there AP courses?|What is the school's ethos?|Are there scholarships?",
            faq_answers="Morning Star is a Christian school and holds regular chapel services, but students of all faiths are welcomed and respected.|Concordia is more selective and academically rigorous for competitive US university preparation. Morning Star offers a more nurturing, faith-focused environment at lower fees.|AP courses are available in senior years. Confirm the current AP subject list with admissions.|Morning Star combines American academic standards with Christian values — emphasising integrity, service, and community alongside academic excellence.|Need-based financial assistance is available for families who require support. Enquire with the school directly.",
        ),

        # ── 25. St Paul American School ──────────────────────────────────
        School(
            name="St Paul American School Hanoi",
            slug="st-paul-american-hanoi",
            curriculum="American Common Core + AP",
            tuition_range="$8,000 – $15,000",
            district="Dong Da",
            image_url=_img(9),
            summary="Affordable American-curriculum school in a central Hanoi location. Good academic foundations and AP options for senior students.",
            accreditation="WASC candidate, College Board (AP)",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.spas.edu.vn",
            founded_year="2007",
            total_students="~500",
            class_size_max="22",
            address="Dong Da, Hanoi",
            facilities="Sports court|Library|Science labs|Computer lab|Arts room",
            pros="Central Dong Da location|American curriculum at competitive fees|AP courses available|Good transition support for US university preparation",
            cons="Not fully WASC-accredited — verify with target US universities|Smaller facilities|Less rigorous AP programme than Concordia",
            university_pathways="AP courses → US university applications. IELTS support for Australian and UK universities.",
            admissions_timeline="Year-round rolling admissions|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records",
            faq_questions="Is St Paul suitable for US college preparation?|Are there AP courses?|How does it compare to Concordia?|Is there an EAL programme?|Are there scholarships?",
            faq_answers="St Paul provides a solid American curriculum foundation. For highly competitive US universities, Concordia's fully accredited AP programme may provide a stronger platform.|AP courses are available in senior years. Confirm the current subject list with admissions.|Concordia is more selective, more expensive, and has a stronger AP programme. St Paul is a good option for families on a tighter budget who want American curriculum.|Yes — EAL support is available across year groups.|Merit and need-based support is available. Enquire with admissions.",
        ),

        # ── 26. TH School ─────────────────────────────────────────────────
        School(
            name="TH School",
            slug="th-school",
            curriculum="IB PYP / MYP / Diploma + Vietnamese MOET",
            tuition_range="$12,000 – $22,000",
            district="Dong Anh",
            image_url=_img(10),
            summary="Premium Vietnamese-managed school with full IB authorisation and stunning modern campus. Strong STEAM and sustainability focus.",
            accreditation="IBO, MOET (Vietnam)",
            language_of_instruction="English + Vietnamese",
            age_range="3–18",
            website_url="https://www.th-school.edu.vn",
            founded_year="2016",
            total_students="~600",
            class_size_max="20",
            address="Dong Anh, Hanoi",
            facilities="Olympic pool|Sports complex|Innovation hub|Performing arts centre|Organic farm|Science labs|Library",
            pros="Spectacular modern campus — some of the best facilities in Hanoi|Full IB continuum|Sustainability and farm-to-table learning|Smaller class sizes than most comparable schools",
            cons="Dong Anh location is north of the Red River — long commute from most of Hanoi|Newer school building track record|Vietnamese + IB dual curriculum demanding for some students",
            university_pathways="IB Diploma → international universities. Growing track record of placements at US, UK, and Australian institutions.",
            admissions_timeline="October: Applications open|February: Scholarship deadline|August: Orientation week",
            required_documents="Application form|School reports|Teacher reference|Passport|Language assessment",
            faq_questions="Where exactly is TH School?|Is TH School affiliated with TH Group?|What are the sustainability initiatives?|Are there scholarships?|How demanding is the bilingual curriculum?",
            faq_answers="TH School is located in Dong Anh district, north of the Red River. It is approximately 30–40 minutes from Hoan Kiem in normal traffic. The school runs a bus service.|Yes — TH School is part of the TH Group (known for TH True Milk) and benefits from significant investment in facilities and curriculum development.|TH School has an organic farm on campus where students grow food, study sustainability, and learn about ecosystems. This is integrated into the IB curriculum.|Merit and need-based scholarships are available. Enquire with admissions for the current cycle.|Students study IB subjects in English and Vietnamese MOET subjects in Vietnamese. It is demanding but most students manage well with the school's bilingual support.",
        ),

        # ── 27. Uppingham Vietnam ─────────────────────────────────────────
        School(
            name="Uppingham Hung Yen",
            slug="uppingham-hung-yen",
            curriculum="British Independent Curriculum + A-Level + IB Diploma",
            tuition_range="$30,000 – $50,000",
            district="Hung Yen",
            image_url=_img(11),
            summary="Iconic British boarding school brand. Full boarding programme, outstanding music and sport, and dual A-Level / IB Diploma exit in a stunning riverside campus.",
            accreditation="ISI, BSO, IBO",
            language_of_instruction="English",
            age_range="11–18",
            website_url="https://www.uppinghamvietnam.com",
            founded_year="2018",
            total_students="~350",
            class_size_max="14",
            address="Hung Yen Province (35km from central Hanoi)",
            facilities="Boarding houses|Concert hall|Multiple sports pitches|Swimming pool|Theatre|Science labs|Art studios|Music practice rooms",
            pros="World-famous UK independent school brand|Full boarding — ideal for expat families on rotation|Exceptional music, sport, and arts provision|Very small classes and intensive pastoral support",
            cons="Most expensive school in the Hanoi region|30–35 minutes from central Hanoi — full boarding model|Secondary only (from age 11)|Hung Yen location feels rural for day families",
            university_pathways="A-Level or IB Diploma → Oxbridge, Russell Group, Ivy League, and global elite universities. Uppingham UK has a history of Oxbridge success.",
            admissions_timeline="October: Applications open|November: Scholarship assessment|January: Main offers|May: Final confirmation|August: School begins",
            required_documents="Application form|Academic transcripts|Head teacher reference|Entrance assessment|Passport|Medical records|Boarding questionnaire",
            faq_questions="Is Uppingham Hung Yen the same as Uppingham UK?|Is it primarily a boarding school?|What scholarships are available?|How is the A-Level vs IB choice made?|What sports are offered?",
            faq_answers="Uppingham Vietnam operates under licence from Uppingham School UK, sharing curriculum philosophy, quality standards, and the house system.|Uppingham Hung Yen is designed primarily as a boarding school. Day places may be available for local families.|Academic, music, sport, and all-round scholarships are available at Year 7 and Year 12 entry — covering up to 30% of fees.|Students and their families choose A-Level or IB Diploma in Year 11, supported by detailed guidance from the Head of Sixth Form.|An extensive sports programme includes rugby, cricket, rowing, hockey, tennis, swimming, and more than 30 additional activities.",
        ),

        # ── 28. Horizon Bilingual School ──────────────────────────────────
        School(
            name="Horizon International Bilingual School",
            slug="horizon-hanoi",
            curriculum="Vietnamese MOET + Cambridge International",
            tuition_range="$6,000 – $12,000",
            district="Dong Da",
            image_url=_img(12),
            summary="Affordable bilingual school delivering both Vietnamese and Cambridge curricula. Strong parent community and growing academic reputation.",
            accreditation="Cambridge International, MOET",
            language_of_instruction="Vietnamese + English",
            age_range="3–18",
            website_url="https://www.horizon.edu.vn",
            founded_year="2009",
            total_students="~1,000",
            class_size_max="26",
            address="Dong Da / multiple campuses, Hanoi",
            facilities="Library|Science labs|Sports hall|Swimming pool (select campuses)|Canteen",
            pros="Very affordable for bilingual education|Cambridge International endorsement|Central Dong Da location|Strong Vietnamese language education",
            cons="Larger class sizes|Less suited for families on short rotations|Some English-medium subjects taught by non-native English speakers",
            university_pathways="Cambridge IGCSE → UK, Australian, or Vietnamese university. English pathway growing with IELTS support.",
            admissions_timeline="Year-round admissions|August: Main intake",
            required_documents="Application form|School reports|Passport|Vaccination records",
            faq_questions="Is Horizon primarily Vietnamese or international?|How good is the English instruction?|Are there scholarships?|Is it suitable for non-Vietnamese speakers?|Which campus is recommended?",
            faq_answers="Horizon serves a primarily Vietnamese-international student body. It is best suited for families with a connection to Vietnam and an interest in Vietnamese language.|English instruction quality has improved significantly in recent years. Cambridge-endorsed subjects are taught to international standards, though Vietnamese subjects are in Vietnamese.|Merit and sibling discounts are available. Enquire with admissions.|Children with no Vietnamese can join with EAL support, but families should plan for a bilingual environment. Best suited to longer-term Hanoi families.|Visit multiple campuses — facilities and quality vary. The Dong Da campus is generally well-regarded.",
        ),

        # ── 29. Westlink International School ────────────────────────────
        School(
            name="Westlink International School Hanoi",
            slug="westlink-hanoi",
            curriculum="British National Curriculum + IGCSE + IB Diploma",
            tuition_range="$12,000 – $22,000",
            district="Nam Tu Liem",
            image_url=_img(13),
            summary="Modern British curriculum school in the west of Hanoi. Growing community, solid IGCSE results, and IB Diploma option from Year 12.",
            accreditation="Cambridge International, IBO candidate",
            language_of_instruction="English",
            age_range="3–18",
            website_url="https://www.westlink.edu.vn",
            founded_year="2014",
            total_students="~500",
            class_size_max="20",
            address="Nam Tu Liem, Hanoi",
            facilities="Sports hall|STEM labs|Library|Swimming pool|Arts studio|Music rooms",
            pros="Growing British curriculum school with improving results|IB Diploma option at sixth form|Modern campus in the rapidly developing west of Hanoi|More affordable than UK independent school brands",
            cons="Newer school — still building track record and alumni network|Smaller sixth form|Nam Tu Liem can be far from northern and eastern expat areas",
            university_pathways="IGCSE → IB Diploma → UK, US, and international university applications.",
            admissions_timeline="Year-round rolling admissions|January: Scholarship round|August: Main intake",
            required_documents="Application form|School reports|Passport|Medical records|Teacher reference",
            faq_questions="Is Westlink IB-accredited?|How does Westlink compare to BIS?|Are there scholarships?|Who is the target student?|What is the university placement record?",
            faq_answers="Westlink is an IBO candidate school for IB Diploma at sixth form. Confirm current accreditation status with admissions.|BIS is more established, more expensive, and has a stronger alumni record. Westlink is a solid alternative for families who prefer the west of the city.|Merit and early-enrolment discounts are available. Enquire with admissions.|Westlink suits expat families in the western Hanoi districts (Nam Tu Liem, Tu Liem, Ha Dong), looking for British or IB education at competitive fees.|Building its placement record — recent graduates have entered UK and Australian universities. Check with admissions for the latest results.",
        ),

        # ── 30. Japanese International School ────────────────────────────
        School(
            name="Japanese International School Hanoi",
            slug="japanese-international-school",
            curriculum="Japanese Ministry of Education Curriculum",
            tuition_range="$5,000 – $10,000",
            district="Tay Ho",
            image_url=_img(14),
            summary="The school of choice for Japanese expat families in Hanoi. Japanese Ministry of Education curriculum ensuring seamless return transitions to Japan.",
            accreditation="Japanese Ministry of Education (MEXT)",
            language_of_instruction="Japanese",
            age_range="6–15",
            website_url="",
            founded_year="1995",
            total_students="~200",
            class_size_max="30",
            address="Tay Ho, Hanoi",
            facilities="Library|Sports hall|Science labs|School lunch service",
            pros="Seamless curriculum continuity for children returning to Japan|Japanese cultural environment and community|Most affordable international school option|Strong community bond among Japanese families",
            cons="Instruction primarily in Japanese — not suitable for non-Japanese speakers|Limited to primary and lower secondary (up to Grade 9)|Few extracurricular options vs larger schools",
            university_pathways="Japanese secondary school diploma → Japanese university entrance. Preparation for Japanese high school re-entry for returning families.",
            admissions_timeline="April: Japanese school year begins|Applications accepted year-round for Japanese national children",
            required_documents="Proof of Japanese nationality|Previous school reports (in Japanese)|Vaccination records|Residence registration in Vietnam",
            faq_questions="Is the Japanese school open to non-Japanese children?|What year groups are available?|Is there a high school programme?|How does the school handle Japanese returning to Japan?|What are the fees?",
            faq_answers="The Japanese International School is primarily for Japanese nationals. Non-Japanese children may be considered in special circumstances — contact the school directly.|Grades 1 through 9 (primary and lower secondary). For high school (Grade 10+), Japanese families typically transition to Japanese online programmes or return to Japan.|The school currently does not have a high school programme. Grade 9 completers return to Japan for high school or may join other international schools in Hanoi.|The curriculum mirrors the Japanese national curriculum exactly — re-entry to Japanese schools is seamless. The school liaises directly with Japanese schools on student transitions.|Fees are significantly lower than most international schools in Hanoi, typically ¥500,000–¥1,200,000 per year depending on year group.",
        ),

        # ── 31. Korea Global School ───────────────────────────────────────
        School(
            name="Korea Global School Hanoi",
            slug="korea-global-school",
            curriculum="Korean Ministry of Education Curriculum",
            tuition_range="$5,000 – $10,000",
            district="Cau Giay",
            image_url=_img(0),
            summary="The primary school choice for Korean expat families in Hanoi. Korean curriculum ensuring smooth re-integration into the Korean education system.",
            accreditation="Korean Ministry of Education",
            language_of_instruction="Korean",
            age_range="6–18",
            website_url="",
            founded_year="2000",
            total_students="~350",
            class_size_max="28",
            address="Cau Giay, Hanoi",
            facilities="Library|Sports hall|Computer lab|School canteen|Music room",
            pros="Seamless curriculum continuity for Korean families|Korean cultural community and support networks|Very affordable fees|Full school from Grade 1 through Grade 12",
            cons="Instruction in Korean only — not suitable for non-Korean families|Curriculum optimised for Korean university entry (Suneung exam)|Limited extracurricular variety compared to international schools",
            university_pathways="Korean high school diploma (Suneung preparation) → Korean university entrance. Growing number of Korean graduates applying to US and Australian universities.",
            admissions_timeline="March: Korean school year begins|Rolling admissions for Korean national students throughout the year",
            required_documents="Proof of Korean nationality or overseas Korean status|Previous school records (in Korean)|Vaccination records|Residence in Vietnam documentation",
            faq_questions="Is the school open to non-Korean students?|Does the school prepare students for Suneung?|Are there any English-medium subjects?|How does the school support families returning to Korea?|What extracurricular activities are offered?",
            faq_answers="The school primarily serves Korean nationals. Non-Korean students with Korean language proficiency may be considered — contact the school.|Yes — the senior programme includes preparation for the Suneung (Korean university entrance exam) and Korean scholastic aptitude.|English is taught as a foreign language subject. Other instruction is in Korean.|The school liaises with Korean schools and education authorities to ensure smooth re-integration for returning students. Academic records are maintained in the Korean format.|Sports, music, Korean cultural activities, and after-school tutoring programmes are offered.",
        ),

    ]

    for s in schools:
        session.add(s)
    session.commit()

    loaded = session.exec(select(School)).all()
    school_map = {s.slug: s.id for s in loaded}

    offers = [
        Offer(school_id=school_map["unis-hanoi"], title="Grade 9 Merit Scholarship 2026", offer_type="Scholarship",
              detail="Partial scholarship covering up to 20% of tuition for academically outstanding Grade 9 applicants. Requires minimum B average and two teacher references.",
              deadline="2026-07-15", source_url="https://www.unishanoi.org/admissions/scholarships", verification_status="School-confirmed"),

        Offer(school_id=school_map["bis-hanoi"], title="Early Enrolment Discount — 5% off tuition", offer_type="Discount",
              detail="5% reduction on full-year tuition for families who confirm and pay deposit before 30 June 2026.",
              deadline="2026-06-30", source_url="https://www.bishanoi.com/admissions/fees", verification_status="School-confirmed"),

        Offer(school_id=school_map["bis-hanoi"], title="Sibling Discount — 10% on second child", offer_type="Discount",
              detail="10% off annual tuition for the second enrolled child. Applies as long as both siblings are enrolled.",
              deadline="2026-12-31", source_url="https://www.bishanoi.com/admissions/fees", verification_status="School-confirmed"),

        Offer(school_id=school_map["concordia-hanoi"], title="AP Excellence Scholarship", offer_type="Scholarship",
              detail="Award value $2,000–$5,000/year (renewable) for incoming Grade 9 and Grade 11 students with demonstrated academic excellence.",
              deadline="2026-12-01", source_url="https://www.concordiahanoi.org/admissions/scholarships", verification_status="Source-verified"),

        Offer(school_id=school_map["lycee-francais-hanoi"], title="AEFE Scholarship for French Nationals", offer_type="Scholarship",
              detail="French government scholarships through the AEFE network. Can cover up to 100% of tuition based on financial need.",
              deadline="2026-05-31", source_url="https://www.lyceeyersin.com/scolarite/bourses", verification_status="School-confirmed"),

        Offer(school_id=school_map["brighton-college-vietnam"], title="Year 7 Academic & Co-Curricular Scholarships", offer_type="Scholarship",
              detail="Awards available for music, sport, academic excellence, and all-round merit. Assessment held in January. Up to 25% of tuition.",
              deadline="2026-01-31", source_url="https://www.brightoncollege.edu.vn/admissions/scholarships", verification_status="Source-verified"),

        Offer(school_id=school_map["reigate-grammar-vietnam"], title="Gamuda Gardens Early Enrolment Offer", offer_type="Discount",
              detail="10% discount on Year 1 tuition for families enrolling before 28 February 2026. Limited places.",
              deadline="2026-02-28", source_url="https://www.rgs.edu.vn/admissions", verification_status="Source-verified", active=False),

        Offer(school_id=school_map["rugby-school-hanoi"], title="Year 7 All-Round Scholarship", offer_type="Scholarship",
              detail="Rugby School Hanoi offers academic, sport, and music scholarships at Year 7 entry. Awards up to 20% of annual tuition.",
              deadline="2026-11-30", source_url="https://www.rugbyschoolhanoi.com/scholarships", verification_status="Source-verified"),

        Offer(school_id=school_map["sis-ciputra"], title="IB Excellence Bursary", offer_type="Scholarship",
              detail="Partial bursary for students entering Year 12 IB Diploma with outstanding IGCSE results. Apply directly through admissions.",
              deadline="2026-06-30", source_url="https://www.sisvietnam.com/admissions", verification_status="Source-verified"),

        Offer(school_id=school_map["parkcity-hanoi"], title="New Family Welcome Discount — 5% first year", offer_type="Discount",
              detail="New families joining ParkCity for the 2026–27 academic year receive a 5% discount on the first year's tuition.",
              deadline="2026-06-15", source_url="https://www.isph.edu.vn/admissions", verification_status="Source-verified"),

        Offer(school_id=school_map["hanoi-international-school"], title="New family welcome: 3 months free school bus", offer_type="Fee Waiver",
              detail="New families joining HIS for 2026–27 receive three months of complimentary school bus service (value ~$450).",
              deadline="2026-07-31", source_url="https://www.hisvietnam.com/admissions", verification_status="Source-verified"),

        Offer(school_id=school_map["uppingham-hung-yen"], title="Year 12 IB Scholarship Assessment", offer_type="Scholarship",
              detail="Academic, music, and sport scholarships for Year 12 IB Diploma entry. Awards 10–30% of fees. Assessment in November 2025.",
              deadline="2026-01-15", source_url="https://www.uppinghamvietnam.com/scholarships", verification_status="Source-verified", active=False),

        Offer(school_id=school_map["dwight-school-hanoi"], title="Spark Scholarship for Creative Learners", offer_type="Scholarship",
              detail="Dwight's signature scholarship for students who demonstrate exceptional creative or intellectual spark across art, science, or community leadership.",
              deadline="2026-08-31", source_url="https://www.dwighthanoi.edu.vn/admissions", verification_status="Source-verified"),

        Offer(school_id=school_map["vas-hanoi"], title="Sibling Enrolment Discount", offer_type="Discount",
              detail="15% tuition discount for the second enrolled child. Applicable across all year groups for the 2026–27 academic year.",
              deadline="2026-07-31", source_url="https://www.vas.edu.vn/admissions/fees", verification_status="School-confirmed"),

        Offer(school_id=school_map["true-north-hanoi"], title="Early Bird Discount — $500 off first year", offer_type="Discount",
              detail="Families confirming enrolment and paying the deposit before 31 March 2026 receive a $500 reduction on Year 1 fees.",
              deadline="2026-03-31", source_url="https://www.truenorth.edu.vn/admissions", verification_status="Source-verified"),
    ]

    for o in offers:
        session.add(o)
    session.commit()
